backend:
  name: github
  repo: aidamn81/candyheals
  branch: main
  base_url: https://sweet-flan-5bb2d9.netlify.app/.netlify/functions/oauth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

media_library:
  name: uploadcare

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content/site.json"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Header Image", name: "headerImage", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
