backend:
  name: git-gateway
  branch: main

site_url: https://sweet-flan-5bb2d9.netlify.app
logo_url: https://sweet-flan-5bb2d9.netlify.app/candyheader.jpg

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

media_library:
  name: file

collections:
  - name: "site"
    label: "Site Content"
    delete: false
    editor: { preview: false }
    files:
      - file: "content/site.json"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Events Text", name: "eventsText", widget: "text" }
          - { label: "Entertainment Types Text", name: "typesText", widget: "text" }
          - { label: "About Text", name: "aboutText", widget: "text" }
          - { label: "Showreel (iframe or HTML)", name: "showreelHTML", widget: "text" }
          - { label: "Header Image", name: "header", widget: "image", allow_multiple: false }
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string", required: false }
          - label: "Background"
            name: "background"
            widget: "object"
            collapsed: true
            fields:
              - { label: "bg1", name: "bg1", widget: "string", default: "#1a0030" }
              - { label: "bg2", name: "bg2", widget: "string", default: "#320046" }
              - { label: "surge1", name: "surge1", widget: "string", default: "#ff2a8a" }
              - { label: "surge2", name: "surge2", widget: "string", default: "#1ea7ff" }
              - { label: "surge3", name: "surge3", widget: "string", default: "#ff3d4f" }
              - { label: "glitter (0–1)", name: "glitter", widget: "number", value_type: "float", min: 0, max: 1, step: 0.05, default: 0.7 }
